# Site settings
title: "ruleles's blog"
email: ruleless@126.com
description: "ruleles's blog."
baseurl: ""
url: ""
title_description: ""
title_image: ""
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
# github_repository: https://github.com/ruleless/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
github_username:  ruleless
# linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
# google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
# stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
